import React from 'react';
import './TermsAndConditions.css'; 

const TermsAndConditions = () => {
  return (
    <div className="terms-conditions-container">
      <h1>Terms and Conditions ("Terms")</h1>
      <section> 
        <p>Our Terms and Conditions were last updated on[DATE]. Please read these terms and conditions carefully before using Our Service.</p> 
      </section>
      <section>
      <h1>Interpretation and Definitions</h1> 
      <p>Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. Definitions For the purposes of these Terms and Conditions:</p>
      <ul>
        <li>“Affiliate” means an entity that controls, is controlledby or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li> 
        <li>“Account” means a unique account created for You toaccess our Service or parts of our Service.</li>
        <li>“Company” (referred to as either "the Company", "We","Us" or "Our" in this Agreement) refers to [COMPANY_INFORMATION].</li>
        <li>“Country” refers to[COMPANY_COUNTRY].</li>
        <li>“Content” refers to content such as text, images,or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content.</li>
        <li>“Device” means any device that can access the Servicesuch as a computer, a cellphone or a digital tablet.</li>
        <li>“Feedback” means feedback, innovations or suggestionssent by You regarding the attributes, performance or features of our Service.</li>
        <li>“Products” refer to the products or items offeredfor sale on the Service.</li>
        <li>“Orders” mean a request by You to purchase Productsfrom Us</li>
        <li>“Promotions” refer to contests, sweepstakes or otherpromotions offered through the Service.</li>
        <li>“Service” refers to the Website.</li> 
        <li>“Terms and Conditions” (also referred as "Terms")mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated byTermsFeed Termsand Conditions Generator.</li> 
        <li>“Third-party Social Media Service” means any servicesor content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.</li>
        <li>“Website” refers to[WEBSITE_NAME], accessible from[WEBSITE_URL]</li>
        <li>“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>
        </section>
        <section>
        <h2>Acknowledgment</h2> 
        <p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service. Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service. By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service. You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service. Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.</p>
        </section>
        <section>
          <h2>User Accounts</h2> 
          <p>When You create an account with Us, You must provide Us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of Your account on Our Service. You are responsible for safeguarding the password that You use to access the Service and for any activities or actions under Your password, whether Your password is with Our Service or a Third-Party Social Media Service. You agree not to disclose Your password to any third party. You must notify Us immediately upon becoming aware of any breach of security or unauthorized use of Your account. You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than You without appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.</p> 
          <p>Here is the link for the terms and conditions... https://www.termsfeed.com/public/uploads/2021/12/sample-terms-conditions-agreement.pdf </p>
          </section>
          
    </div>
  );
}

export default TermsAndConditions;
